info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples_percy
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka2/
      
foo: percy ivan quispe
---
spring:
  profiles: cloud
  cloud:
    config:
      uri: http//peru.com-
--
spring:
  profiles: cloud2
  cloud:
    config:
      uri: http//peru2.com